- name: configure HAProxy
  template:
    src: ./haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify:
  - restart HAProxy  

handlers:
  - name: restart HAProxy
    service:
      name: haproxy
      state: restarted