--- 
- 
  handlers: 
    - name: "restart HAProxy"
      service: 
        name: haproxy
        state: restarted
  
  name: "configure HAProxy"
  template: 
    dest: /etc/haproxy/haproxy.cfg
    src: haproxy.cfg.j2
  notify: 
    - "restart HAProxy"

